apiVersion: batch/v1
kind: CronJob
metadata:
  name: staleb-calicot-function-cron
  namespace: dev
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: staleb-calicot-function
              image: kubechallengeacr.azurecr.io/staleb-calicot-function:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: AzureWebJobsStorage
                  valueFrom:
                    configMapKeyRef:
                      name: "calicot-configmap"
                      key: "AzureWebJobsStorage"
          restartPolicy: OnFailure
