apiVersion: apps/v1
kind: Deployment
metadata:
  name: calicot-ui
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calicot-ui
  template:
    metadata:
      labels:
        app: calicot-ui
    spec:
      containers:
        - name: calicot-ui
          image: kubechallengeacr.azurecr.io/staleb-calicot-ui:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv"
