apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: staleb-calicot-services-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staleb-calicot-services
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70