apiVersion: batch/v1
kind: CronJob
metadata:
  name: staleb-calicot-function-cron
  namespace: dev
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: staleb-calicot-function
              image: kubechallengeacr.azurecr.io/staleb-calicot-function:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
